# Generated by Django 4.2.3 on 2023-07-10 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('RunningStringServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='string',
            new_name='s',
        ),
    ]
